import { Metadata } from "next";

/**
 * Metadata for the site.
 * Modify it to fit the specific needs of your app
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
